version: '3'

services:
  server:
    image: nginx:latest
    working_dir: /var/www/html/docroot
    ports:
      - "80:80"
      - "443:443"
    links:
      - db:${APP_URL}
      - fpm
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./etc/nginx/ssl:/etc/nginx/ssl:delegated
      - ./docroot:/var/www/html/docroot:cached

  fpm:
    image: catchdigital/php:7.4.25-fpm
    working_dir: /var/www/html/docroot
    env_file: .env
    expose:
      - 9000
    links:
      - db:${APP_URL}
    volumes:
      - ./docker/etc/php/config.ini:/usr/local/etc/php/conf.d/x-config.ini:cached
      - ./.:/var/www/html:cached

  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    volumes:
       - drucker-mariadb:/var/lib/mysql
       - ./etc/mysql/conf.d:/etc/mysql/conf.d:cached
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}

  # memcached:
  #   image: memcached:1.6.12-alpine

  # node-sass:
  #   image: catchdigital/awscli:2.3.0
  #   user: '1000'
  #   command: bash -c "npm install && npm run build"
  #   working_dir: /var/www/html/docroot/themes/custom/catchify_theme
  #   volumes:
  #     - ./.:/var/www/html

  # composer:
  #   image: composer:2
  #   command: install --no-dev --no-interaction --optimize-autoloader --ignore-platform-reqs
  #   working_dir: /var/www/html
  #   volumes:
  #     - ./.:/var/www/html

volumes:
  drucker-mariadb:
