server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name catchdigital.com;
	return 301 https://$host$request_uri;
}

server {
    # Enable http2 and http3
    http2 on;
    listen 443 ssl;
    listen [::]:443 ssl;

    http3 on;
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;
    add_header Alt-Svc 'h3=":443"; ma=86400';

    root /var/www/html/docroot;
    index index.php index.html index.htm;

    # Set SSL
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Returns storybook endpoint from drupal
    location /storybook/stories/ {
        try_files $uri /index.php$is_args$args;
    }

    # Returns storybook from node server
    location /storybook {
        rewrite ^/storybook(.*) /storybook/$1 permanent;
    }

    location /storybook/ {
        proxy_pass http://storybook:6006/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Default drupal behaviour
    location ~ ^/.+\.php(/|$) {
        fastcgi_buffers 16 32k;
        fastcgi_buffer_size 64k;
        fastcgi_pass fpm:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Set 500 error page
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html;
      internal;
    }

}
